package llm

import (
	"context"
	"fmt"
	"strings"
	"time"
)

// MockProvider generates deterministic release-note text for local testing.
type MockProvider struct{}

func (p *MockProvider) Generate(_ context.Context, prompt string) (Generation, error) {
	snippet := strings.TrimSpace(prompt)
	if len(snippet) > 160 {
		snippet = snippet[:160] + "..."
	}

	text := fmt.Sprintf(
		"### Summary\nGenerated by mock provider at %s.\n\n### Changes\n- This is a simulated release note output for local testing.\n- Prompt snippet: %q\n\n### Impact / Breaking Changes\nNone.\n\n### Notes\nSwitch `LLM_PROVIDER` to a real backend when ready.",
		time.Now().UTC().Format(time.RFC3339),
		snippet,
	)
	return Generation{
		Text: text,
		Usage: Usage{
			InputTokens:  estimateTokens(prompt),
			OutputTokens: estimateTokens(text),
		},
	}, nil
}

func (p *MockProvider) Model() string {
	return "mock-model"
}

func estimateTokens(s string) int {
	// Lightweight approximation: ~4 characters per token.
	n := len(strings.TrimSpace(s))
	if n == 0 {
		return 0
	}
	return (n + 3) / 4
}
